version: '2'

volumes:
  db:
  redis:
  cert_cache:
  soundboard:

networks:
  default:

services:
  app:
          #image: teyker/yagpdb:master-rootless
    image: shatindle/yagpdb-arceus:latest
    restart: unless-stopped
    stdin_open: true
    tty: true
    #command:
            #- "/home/yagpdbbot/yagpdb"
            #- "-all"
            #- "-exthttps=true"
            #- "-https=false"
    depends_on:
      - redis
      - db
    networks:
      - default
    volumes:
            #- cert_cache:/home/yagpdbbot/cert
      - cert_cache:/cert
        #- soundboard:/home/yagpdbbot/soundboard
      - soundboard:/soundboard
    ports:
      - '5009:5000'
      - '5010:5001'
    env_file:
      - .env

  redis:
    image: redis
    restart: unless-stopped
    networks:
      - default
    volumes:
      - redis:/data

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    networks:
      - default
    ports:
      - '5011:80'
    env_file:
      - .env

  backup-svc:
    image: shatindle/yagpdb-backup-service:latest
    restart: unless-stopped
    networks:
      - default
    depends_on:
      - redis
      - db
    env_file:
      - .env

  db:
    image: postgres:11
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - default
    env_file:
      - .env