version: '3'

volumes:
  db:
  redis:
  cert_cache:
  soundboard:

networks:
  default:

services:
  app:
    build:
      context: ../yagpdb
      dockerfile: ../arceus-yagpdb/Dockerfile.yagpdb
    restart: unless-stopped
    stdin_open: true
    tty: true
    command:
      - "/app/yagpdb"
      - "-all"
      - "-pa"
      - "-exthttps=false"
      - "-https=true"
    depends_on:
      - redis
      - db
    networks:
      - default
    volumes:
      #- cert_cache:/home/yagpdbbot/cert
      - cert_cache:/cert
      #- soundboard:/home/yagpdbbot/soundboard
      - soundboard:/soundboard
    ports:
      - '5009:5000'
      - '5010:5001'
    env_file:
      - .env

  redis:
    image: redis
    restart: unless-stopped
    networks:
      - default
    volumes:
      - redis:/data

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    networks:
      - default
    ports:
      - '5011:80'
    env_file:
      - .env

  backup-svc:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - default
    depends_on:
      - redis
      - db
    env_file:
      - .env

  db:
    image: postgres:11
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - default
    env_file:
      - .env